name: quebragalho2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  lottie: ^2.7.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  http: ^0.13.6
  mask_text_input_formatter: ^2.9.0
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/confetti.json
    - assets/welcome.json
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
