name: flutter_quebragalho
description: "Aplicativo Quebra Galho para android"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_28pt-ExtraBold.ttf
          weight: 900