// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF8YS2GMI1R3a2FSY2BqqfIs6WZSI5Ge8',
    appId: '1:461538889702:web:a29b06524c8feadeed9027',
    messagingSenderId: '461538889702',
    projectId: 'quebragalho-b86d5',
    authDomain: 'quebragalho-b86d5.firebaseapp.com',
    storageBucket: 'quebragalho-b86d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6mJcqWPElRPClMARmyyylM6k6VIMYX8',
    appId: '1:461538889702:android:df79c9c1f5cd7e06ed9027',
    messagingSenderId: '461538889702',
    projectId: 'quebragalho-b86d5',
    storageBucket: 'quebragalho-b86d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFqjlBlxKKhIyHCmpTADvElwgSZW6ezBk',
    appId: '1:461538889702:ios:76a10c6ae6599f95ed9027',
    messagingSenderId: '461538889702',
    projectId: 'quebragalho-b86d5',
    storageBucket: 'quebragalho-b86d5.firebasestorage.app',
    iosBundleId: 'com.example.quebragalho2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFqjlBlxKKhIyHCmpTADvElwgSZW6ezBk',
    appId: '1:461538889702:ios:76a10c6ae6599f95ed9027',
    messagingSenderId: '461538889702',
    projectId: 'quebragalho-b86d5',
    storageBucket: 'quebragalho-b86d5.firebasestorage.app',
    iosBundleId: 'com.example.quebragalho2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF8YS2GMI1R3a2FSY2BqqfIs6WZSI5Ge8',
    appId: '1:461538889702:web:aefab23c0dcfa418ed9027',
    messagingSenderId: '461538889702',
    projectId: 'quebragalho-b86d5',
    authDomain: 'quebragalho-b86d5.firebaseapp.com',
    storageBucket: 'quebragalho-b86d5.firebasestorage.app',
  );
}
